import type {GetStaticProps, NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Layout from "../components/Layout";
import {getAllPostData} from "../lib/Posts/posts.utils";

export async function getStaticProps(props: GetStaticProps){
  return {
    props : {
      posts: getAllPostData()
    }
  }
}

interface AboutProps {
  posts?: {
    id: string;
    title: string;
    date: string;
  }[]
}

const About: NextPage<AboutProps> = (props) => {
  return (
    <Layout>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          About me
        </h1>

        <Link href='/'>
          go back

        </Link>

        <ul>
          {props.posts?.map(item => (
            <li key={item.id}>{item.title}: {item.date}</li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Layout>
  )
}

export default About
